name: Container

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/devcontainer.yml'
      - '.github/workflows/unit_test.yml'

jobs:
  build-and-push-container:
    runs-on: self-hosted
    if: github.repository_owner == 'deepmodeling'
    strategy:
      matrix:
        dockerfile: ["main"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Aliyun Registry
        uses: docker/login-action@v3
        with:
          registry: registry.dp.tech
          username: ${{ secrets.DP_HARBOR_USERNAME }}
          password: ${{ secrets.DP_HARBOR_PASSWORD }}

      - name: Build and Push Container
        uses: docker/build-push-action@v5
        with:
          tags: |
            ghcr.io/deepmodeling/deeptb-${{ matrix.dockerfile }}:latest
            registry.dp.tech/deepmodeling/deeptb-${{ matrix.dockerfile }}:latest
          file: Dockerfile.${{ matrix.dockerfile }}
          cache-from: type=registry,ref=ghcr.io/deepmodeling/deeptb-${{ matrix.dockerfile }}:latest
          cache-to: type=inline
          push: true